name: BuildWithMeson

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CONAN_REVISIONS_ENABLED: 1

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install Ninja
      id: ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      
    - name: Configure Conan
      run: conan profile detect
      
    - name: Install Meson
      id: meson
      run: pip3 install meson

    - name: Build
      run: sh ./build_meson.sh    
